---
- name: Listen for approved requested items from ServiceNow
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5003

  rules:

    - name: Get Flow info from SNOW
     condition: event.payload.short_description  == "Aschoenf - AAP Linux Provision"
      action:
        run_job_template:
          name: "print snow output"
          organization: "Default"
          job_args:
            extra_vars:
              ticket_number: "{{ event.payload.number }}"
              ticket_sys_id: "{{ event.payload.sys_id }}"

#    - name: Run the linux daily demo workflow
#      condition: event.payload.short_description  == "Ames AAP Linux AWS Daily Demo"
#      action:
#        run_workflow_template:
#          name: "Run workflow for the Linux Daily Demo"
#          organization: "AmesCO"
#          job_args:
#            extra_vars:
#              ticket_number: "{{ event.payload.number }}"
#              ticket_sys_id: "{{ event.payload.sys_id }}"

    - name: Provision VM in OCP  
      condition: event.payload.short_description  == "Control01 Ansible Automation Platform (AAP) automated vulnerability remediation"
      action:
        run_job_template:
          name: "OpenShift / CNV / Create RHEL VM"
          organization: "Default"
          job_args:
            extra_vars:
              ticket_number: "{{ event.payload.number }}"
              ticket_sys_id: "{{ event.payload.sys_id }}"
